### ISSUE TITLE
ERROR: Operation failed with status: 'Bad Request'. Details: 'ImageTemplate': Missing field 'identity'"

### ISSUE THREAD

**Issue by danielsollondon** [danielsollondon/azvmimagebuilder#39]
You will start seeing this error from the 26th May, if your templates do not include 'identity'.

Please review the [May 2020 Service Update](https://github.com/danielsollondon/azvmimagebuilder/blob/master/MayServiceAlert01.md#service-update-may-2020-action-needed---please-review)

**Comment by rossdotpink** [comment]
FWIW I have been building against `2020-02-14` for over a week now and suddenly this morning I have started to receive the following error when attempting to create a template:

`Operation failed with status: 'Bad Request'. Details: Validation failed: 'ImageTemplate': Missing field 'identity'. Please review http://aka.ms/azvmimagebuildertmplref for details on fields required in the Image Builder Template.`

Which is odd because the `identity` field is not only present, but it has been working for a few days now.

**Comment by danielsollondon** [comment]
Closing, as this update was rolled out a while ago.
